// Reusable procedural props for level building.
import * as THREE from 'three';
import { T, std, texMat, M } from './world.js';
import { canvasTex, rand } from './util.js';
const col = c => std('c' + c, { color: c, roughness: 0.7 });
const metal = c => std('m' + c, { color: c, roughness: 0.35, metalness: 0.8 });
const emis = (c, i = 2) => std('e' + c + i, { color: c, emissive: c, emissiveIntensity: i, roughness: 0.5 });
export const PM = { col, metal, emis };
export function windowTex(base = '#6a3a2a', lit = 0.4, cols = 4, rows = 3, frame = '#ddd') {
  return M('wtex' + base + lit + cols + rows + frame, () => canvasTex(256, 256, (x, w, h) => { x.fillStyle = base; x.fillRect(0, 0, w, h); const cw = w / cols, rh = h / rows; for (let i = 0; i < cols; i++) for (let j = 0; j < rows; j++) { x.fillStyle = frame; x.fillRect(i * cw + cw * 0.18, j * rh + rh * 0.15, cw * 0.64, rh * 0.62); x.fillStyle = Math.random() < lit ? '#ffd98a' : '#1d2630'; x.fillRect(i * cw + cw * 0.22, j * rh + rh * 0.19, cw * 0.56, rh * 0.54); } }, { repeat: [1, 1] }));
}
export function building(W, x, z, w, d, h, o = {}) {
  const base = o.color || '#7a4a3a'; const tex = windowTex(base, o.lit !== undefined ? o.lit : 0.35, o.cols || 4, o.rows || 3, o.frame || '#d8d2c4');
  tex.repeat.set(Math.max(1, Math.round(w / 6)), Math.max(1, Math.round(h / 6)));
  const mat = M('bld' + base + w + h + (o.lit || 0), () => new THREE.MeshStandardMaterial({ map: tex, roughness: 0.8, emissive: 0xffffff, emissiveMap: o.glow ? tex : null, emissiveIntensity: o.glow ? 0.25 : 0 }));
  W.box(x, 0, z, w, h, d, mat, { ry: o.ry || 0 }); W.box(x, h, z, w + 0.4, 0.4, d + 0.4, col(o.trim || '#3a3530'), { ry: o.ry || 0, collide: false });
}
export function car(W, x, z, ry = 0, color = '#a33') {
  const g = new THREE.Group(); const body = new THREE.Mesh(new THREE.BoxGeometry(1.8, 0.7, 4.2), std('car' + color, { color, roughness: 0.25, metalness: 0.6 })); body.position.y = 0.6; g.add(body);
  const cab = new THREE.Mesh(new THREE.BoxGeometry(1.6, 0.6, 2.2), std('glass', { color: 0x1a2530, roughness: 0.05, metalness: 0.9 })); cab.position.set(0, 1.2, -0.2); g.add(cab);
  for (const sx of [-0.85, 0.85]) for (const sz of [-1.35, 1.35]) { const w = new THREE.Mesh(new THREE.CylinderGeometry(0.34, 0.34, 0.24, 12), col('#111')); w.rotation.z = Math.PI / 2; w.position.set(sx, 0.34, sz); g.add(w); }
  const hl = new THREE.Mesh(new THREE.BoxGeometry(1.5, 0.12, 0.05), emis('#fff6d0', 1)); hl.position.set(0, 0.7, 2.11); g.add(hl); const tl = new THREE.Mesh(new THREE.BoxGeometry(1.5, 0.12, 0.05), emis('#ff2020', 1)); tl.position.set(0, 0.7, -2.11); g.add(tl);
  g.position.set(x, 0, z); g.rotation.y = ry; W.add(g); const c = Math.abs(Math.cos(ry)), s = Math.abs(Math.sin(ry)); const hw = (1.8 * c + 4.2 * s) / 2, hd = (1.8 * s + 4.2 * c) / 2; W.collider(x - hw, x + hw, z - hd, z + hd, 0, 1.5); return g;
}
export function truck(W, x, z, ry = 0, color = '#2a2a2a', label) {
  const g = new THREE.Group(); const body = new THREE.Mesh(new THREE.BoxGeometry(2.1, 1.0, 5.4), std('trk' + color, { color, roughness: 0.3, metalness: 0.6 })); body.position.y = 0.95; g.add(body);
  const cab = new THREE.Mesh(new THREE.BoxGeometry(2.0, 0.8, 1.9), std('glass', { color: 0x1a2530, roughness: 0.05, metalness: 0.9 })); cab.position.set(0, 1.8, 0.6); g.add(cab);
  for (const sx of [-1, 1]) for (const sz of [-1.7, 1.7]) { const w = new THREE.Mesh(new THREE.CylinderGeometry(0.45, 0.45, 0.35, 12), col('#111')); w.rotation.z = Math.PI / 2; w.position.set(sx, 0.45, sz); g.add(w); }
  g.position.set(x, 0, z); g.rotation.y = ry; if (W) W.add(g); return g;
}
export function tree(W, x, z, s = 1, o = {}) {
  W.cyl(x, 0, z, 0.12 * s, 0.18 * s, 2.2 * s, std('bark', { color: 0x4a3626, roughness: 0.9 }), { collide: true, seg: 7 });
  const leaf = std('leaf' + (o.color || ''), { color: o.color || 0x2f5a26, roughness: 0.85, flatShading: true });
  for (let i = 0; i < 3; i++) { const g = new THREE.IcosahedronGeometry((1.3 - i * 0.25) * s, 0); g.translate(x + rand(-.3, .3) * s, (2.4 + i * 0.8) * s, z + rand(-.3, .3) * s); W.geo(g, leaf); }
}
export function pine(W, x, z, s = 1) { W.cyl(x, 0, z, 0.1 * s, 0.16 * s, 1.2 * s, std('bark', { color: 0x4a3626, roughness: 0.9 }), { collide: true, seg: 6 }); const m = std('pine', { color: 0x1f4424, roughness: 0.9, flatShading: true }); for (let i = 0; i < 3; i++) { const g = new THREE.ConeGeometry((1.4 - i * 0.35) * s, 1.8 * s, 7); g.translate(x, (1.6 + i * 1.0) * s, z); W.geo(g, m); } }
export function lamp(W, x, z, h = 4.5, light = true, color = 0xffe2b0) { W.cyl(x, 0, z, 0.07, 0.09, h, metal('#2a2c30'), { collide: true, seg: 8 }); W.box(x, h, z, 0.5, 0.15, 0.25, emis('#fff1c8', 2), { collide: false }); if (light) return W.pointLight(x, h - 0.3, z, color, 12, 16); }
export function bench(W, x, z, ry = 0) { const wd = texMat('benchw', T.wood('#6a4a2a')); W.box(x, 0.42, z, 1.8, 0.07, 0.45, wd, { ry, collide: false }); W.box(x, 0, z, 1.6, 0.42, 0.3, metal('#222'), { ry }); W.box(x + Math.sin(ry) * -0.2, 0.5, z + Math.cos(ry) * -0.2, 1.8, 0.4, 0.06, wd, { ry, collide: false }); }
export function table(W, x, z, w = 1.6, d = 0.9, mat, h = 0.76) { const m = mat || texMat('tablew', T.wood('#8a6a4a')); W.box(x, h - 0.05, z, w, 0.05, d, m, { collide: false }); W.box(x, 0, z, w * 0.9, h - 0.05, d * 0.9, col('#3a3a3a'), { kind: 'low' }); }
export function shelf(W, x, z, w, h = 2.4, ry = 0) { const bm = texMat('books', T.books()); bm.map.repeat.set(w / 1.6, h / 2.4); W.box(x, 0, z, w, h, 0.5, bm, { ry, tile: 0 }); W.box(x, h, z, w + 0.1, 0.06, 0.55, texMat('shelfw', T.wood('#5a3a20')), { ry, collide: false }); }
export function bed(W, x, z, ry = 0) { W.box(x, 0, z, 1.0, 0.55, 2.1, metal('#9aa0a6'), { ry, kind: 'low' }); W.box(x, 0.55, z, 0.95, 0.14, 2.0, col('#e8eef2'), { ry, collide: false }); const px = x - Math.sin(ry) * 0.8, pz = z - Math.cos(ry) * 0.8; W.box(px, 0.69, pz, 0.7, 0.1, 0.35, col('#ffffff'), { ry, collide: false }); }
export function curtain(W, x, z, w, ry = 0) { W.box(x, 0.3, z, w, 1.9, 0.05, std('curt', { color: 0x8fb8c8, roughness: 0.9, side: THREE.DoubleSide }), { ry, collide: false }); }
export function vending(W, x, z, ry = 0, label = 'Fizz-Ola') { const t = M('vendT' + label, () => canvasTex(128, 256, (k) => { k.fillStyle = '#c8102e'; k.fillRect(0, 0, 128, 256); k.fillStyle = '#111'; k.fillRect(10, 40, 80, 170); for (let i = 0; i < 5; i++) for (let j = 0; j < 4; j++) { k.fillStyle = `hsl(${(i * 70 + j * 30) % 360},70%,55%)`; k.fillRect(16 + j * 18, 50 + i * 32, 14, 22); } k.fillStyle = '#fff'; k.font = "bold 22px 'Black Ops One'"; k.textAlign = 'center'; k.fillText(label, 64, 30); k.fillStyle = '#333'; k.fillRect(98, 90, 22, 40); })); const m = new THREE.MeshStandardMaterial({ map: t, emissive: 0xffffff, emissiveMap: t, emissiveIntensity: 0.35, roughness: 0.4 }); const g = new THREE.Mesh(new THREE.BoxGeometry(0.9, 1.9, 0.8), [col('#8a0a1a'), col('#8a0a1a'), col('#8a0a1a'), col('#8a0a1a'), m, col('#8a0a1a')]); g.position.set(x, 0.95, z); g.rotation.y = ry; W.add(g, { collide: true }); return g; }
export function stall(W, x, z, ry = 0, a = '#ffffff', b = '#d8323c', goods = '#e8742a') { const st = texMat('awn' + a + b, T.stripes(a, b)); const g = new THREE.Group(); const roof = new THREE.Mesh(new THREE.BoxGeometry(3, 0.08, 2.4), st); roof.position.y = 2.4; roof.rotation.x = 0.12; g.add(roof); for (const sx of [-1.4, 1.4]) for (const sz of [-1.1, 1.1]) { const p = new THREE.Mesh(new THREE.CylinderGeometry(0.04, 0.04, 2.4, 6), metal('#ccc')); p.position.set(sx, 1.2, sz); g.add(p); } const tb = new THREE.Mesh(new THREE.BoxGeometry(2.8, 0.85, 0.9), texMat('stallw', T.wood('#8a6a4a'))); tb.position.set(0, 0.42, 0.6); g.add(tb); for (let i = 0; i < 9; i++) { const f = new THREE.Mesh(new THREE.SphereGeometry(0.11, 8, 6), col(goods)); f.position.set(-1.1 + (i % 5) * 0.5, 0.95, 0.45 + Math.floor(i / 5) * 0.3); g.add(f); } g.position.set(x, 0, z); g.rotation.y = ry; W.add(g); const c = Math.abs(Math.cos(ry)), s = Math.abs(Math.sin(ry)); const ox = Math.sin(ry) * 0.6, oz = Math.cos(ry) * 0.6; W.collider(x + ox - (2.8 * c + 0.9 * s) / 2, x + ox + (2.8 * c + 0.9 * s) / 2, z + oz - (2.8 * s + 0.9 * c) / 2, z + oz + (2.8 * s + 0.9 * c) / 2, 0, 0.9); return g; }
export function pumpkins(W, x, z, n = 10) { const m = std('pump', { color: 0xe8742a, roughness: 0.6 }); let k = 0; for (let l = 0; l < 3 && k < n; l++) for (let i = 0; i < 4 - l && k < n; i++, k++) { const g = new THREE.SphereGeometry(0.3, 10, 8); g.scale(1, 0.75, 1); g.translate(x + (i - (3 - l) / 2) * 0.62, 0.22 + l * 0.42, z); W.geo(g, m); } W.collider(x - 1.3, x + 1.3, z - 0.4, z + 0.4, 0, 1.2); }
export function hay(W, x, z, ry = 0) { W.box(x, 0, z, 1.2, 0.6, 0.6, std('hay', { color: 0xd8b25a, roughness: 1 }), { ry }); }
export function chairRow(W, x, z, n, ry = 0) { const m = std('chairb', { color: 0x2a4a7a, roughness: 0.6 }); for (let i = 0; i < n; i++) { const ox = Math.cos(ry) * i * 0.6, oz = -Math.sin(ry) * i * 0.6; W.box(x + ox, 0.42, z + oz, 0.5, 0.08, 0.5, m, { ry, collide: false }); W.box(x + ox - Math.sin(ry) * 0.22, 0.5, z + oz - Math.cos(ry) * 0.22, 0.5, 0.5, 0.06, m, { ry, collide: false }); } W.collider(Math.min(x, x + Math.cos(ry) * (n - 1) * 0.6) - 0.3, Math.max(x, x + Math.cos(ry) * (n - 1) * 0.6) + 0.3, Math.min(z, z - Math.sin(ry) * (n - 1) * 0.6) - 0.3, Math.max(z, z - Math.sin(ry) * (n - 1) * 0.6) + 0.3, 0, 0.9, 'low'); }
export function stringLights(W, x1, z1, x2, z2, h = 3.5, n = 16) { const cols = [0xff5050, 0xffd84a, 0x50ff80, 0x50a0ff, 0xff70d0]; const geo = new THREE.SphereGeometry(0.06, 6, 4); for (let i = 0; i <= n; i++) { const t = i / n; const sag = Math.sin(t * Math.PI) * 0.6; const m = new THREE.Mesh(geo, emis('#' + new THREE.Color(cols[i % 5]).getHexString(), 3)); m.position.set(x1 + (x2 - x1) * t, h - sag, z1 + (z2 - z1) * t); W.group.add(m); } }
export function bike(W, x, z, ry = 0) { const g = new THREE.Group(); const fr = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.35, 1.5), std('bikeR', { color: 0x111111, roughness: 0.3, metalness: 0.8 })); fr.position.y = 0.6; g.add(fr); const tank = new THREE.Mesh(new THREE.SphereGeometry(0.22, 10, 8), std('tank', { color: 0x8a1010, roughness: 0.2, metalness: 0.7 })); tank.scale.set(1, 0.8, 1.6); tank.position.set(0, 0.85, 0.2); g.add(tank); for (const sz of [-0.7, 0.75]) { const w = new THREE.Mesh(new THREE.TorusGeometry(0.32, 0.09, 6, 16), col('#111')); w.rotation.y = Math.PI / 2; w.position.set(0, 0.36, sz); g.add(w); } const hb = new THREE.Mesh(new THREE.BoxGeometry(0.8, 0.04, 0.04), metal('#ccc')); hb.position.set(0, 1.1, 0.7); g.add(hb); g.position.set(x, 0, z); g.rotation.y = ry; if (W) { W.add(g); W.collider(x - 0.6, x + 0.6, z - 0.6, z + 0.6, 0, 1); } return g; }
export function grill(W, x, z) { W.cyl(x, 0.75, z, 0.4, 0.35, 0.3, col('#151515'), { collide: false }); W.cyl(x, 0, z, 0.04, 0.04, 0.8, metal('#333'), { collide: true }); }
export function cooler(W, x, z, ry = 0) { W.box(x, 0, z, 0.8, 0.45, 0.45, std('cooler', { color: 0x1f6fbf, roughness: 0.4 }), { ry }); W.box(x, 0.45, z, 0.82, 0.08, 0.47, col('#f2f2f2'), { ry, collide: false }); }
