// All dialogue. Shayla swears a lot (uncensored, 18+). Movie riffs are reworded parodies, never long verbatim quotes.
export const BARKS = {
  kill: [
    'Get away from my patients, you bitch.',
    'Yippee-ki-yay, motherfucker. Visiting hours are OVER.',
    "I'll be back... with a bigger fucking gun.",
    'Say hello to my little friend. Her name is Glock.',
    'Hasta la vista, bedpan.',
    "I'm not a hero. I'm a nurse with a twelve-hour shift and zero fucks left.",
    "Do I feel lucky? Well, do ya, punk? 'Cause I triaged you as DEAD.",
    'I have a very particular set of skills. Mostly IVs and headshots.',
    'Code Brown, motherfuckers.',
    'Time of death: right fucking now.',
    "Charting that as 'deceased.' Again.",
    "You're discharged. Permanently.",
    'Sit DOWN, sir. Thank you.',
    "That's what you get for pulling out your own IV, asshole.",
    "Nobody puts Shayla in the break room.",
    "Welcome to the jungle, bitch. We got fun and games and a fuckton of bullets.",
    "Go ahead. Make my shift.",
    "Fasten your seatbelts. It's gonna be a bumpy fucking night.",
    "I see dead people. I shoot dead people.",
    "May the force be with you. The force is a nine millimeter.",
    "You had me at 'braaains.' Not really. Die.",
    "Houston, we have a shitload of problems.",
    "Here's Shayla!",
    "There's no crying in triage!",
    "Ten minutes left on my shift and you pull this shit?",
    "I took an oath. It did NOT cover this.",
    "Damn it, I just did my nails.",
    "Rest in pieces, Gary.",
    "That's a DNR if I ever saw one.",
    "Bite me. No. Wait. Don't.",
    "Cool story, corpse.",
    "Ope. Sorry. Not sorry.",
    "You're gonna need a bigger body bag.",
    "Somebody page housekeeping. Aisle fucking everywhere.",
    "I've charted worse. Not much worse.",
    "Shut up and bleed.",
    "Zero stars. Would not resuscitate.",
    "Fuck around. Find out. Get shot.",
  ],
  headshot: [
    'HEADSHOT. Somebody write that in the chart.',
    'Clean through the frontal lobe. Textbook.',
    'Brains: located. Brains: removed.',
    "That's a Glasgow Coma Scale of fuck-you.",
    "Pupils fixed and dilated. And all over the wall.",
    'Head-to-toe assessment: no head.',
    'Aim higher. The brain is up there. Usually.',
    'Boom. Neuro checks negative.',
    "Mind blown. Literally.",
    "Should've worn a helmet, dumbass.",
    "Don't lose your head. Oops.",
    "Ooh, that's gonna leave a mark. On the ceiling.",
    "Lobotomy, express lane.",
  ],
  multi: [
    "Mass casualty event? Hell yes it is.",
    "Two for one! Freddo's should hire me.",
    "Triage that, motherfuckers!",
    "Like bowling, but with assholes.",
  ],
  gib: [
    "Oh, that's disgusting. Do it again.",
    "Arm's off. You won't be needing it.",
    "Somebody's gonna need a LOT of sutures.",
    "That one came apart like cheap scrubs.",
    "Pieces! Little pieces!",
    "'Tis but a scratch? Bitch, that's your whole arm.",
  ],
  reload: [
    'Reloading! Cover me!',
    'Changing mags, hold your shit!',
    "Hang on, sweetie, mama's reloading.",
    'Reloading. Nobody touch me.',
    'Fresh mag. Fresh attitude.',
    'Locked and fucking loaded.',
    'Reload! Reload! Shit shit shit!',
    'Gimme a sec, I got this.',
    "Thirty seconds of peace, that's all I ask.",
  ],
  lowhp: [
    "I'm bleeding. That's fine. That's fine.",
    "I need a medic. Wait. I AM the medic. FUCK.",
    "Okay, that one hurt like a bitch.",
    "Tell Kennedy I loved him. And his stupid guns.",
    "Not today, Satan. Not on my shift.",
    "My blood pressure is NOT okay right now.",
    "Somebody hand me a goddamn bandage!",
    "Ow ow OW, you bit me, you nasty fuck!",
  ],
  hurt: ["Ow! Fuck!", "Son of a bitch!", "Get OFF me!", "Back the fuck up!", "Hands to yourself!", "Ah! Shit!"],
  levelStart: [
    "Alright, assholes. Shift's starting.",
    "Clocking in. God help every one of you.",
    "Let's get this over with. I have a reunion to get to.",
    "Rule number one: don't die. Rule number two: shoot everything.",
    "New location, same bullshit.",
    "Somebody better have coffee in here.",
    "I'm a nurse. I've seen worse. Okay, not THIS.",
  ],
  kennedyArrive: [
    "There's my man! Took you long enough!",
    "Babe! You brought the WHOLE collection?! ...Good.",
    "Kennedy, I swear to God, if you posted this on Facebook...",
    "My hero. My broke, gun-hoarding hero.",
    "About fucking time, babe!",
  ],
  pickupBurger: ["Steakburgers! The family's gonna eat tonight!", "Bag secured. Nobody touch the fries.", "Mmm. Smells like grease and victory."],
  pickupCoke: ["Cokes! Hell yes!", "Ice cold. Like my heart.", "One more case for the reunion."],
  bedpan: ["Ma'am, that is NOT how you use a bedpan.", "BONK.", "Bedpan to the face, bitch!", "Clean THAT up.", "Sanitary? No. Effective? Yes."],
  shoot: ["Eat lead!", "Take your meds!", "Hold still, this'll sting!", "Lie DOWN, sir!"],
  boss: ["Oh, you're a big one. Fuck you anyway.", "Okay, big boy. Let's dance.", "I'm gonna need a bigger gun. Kennedy?!", "What the HELL is that?!"],
  bossDown: ["And STAY down.", "Big ones fall harder.", "Discharged. Against medical advice.", "Boss fight? More like boss bite-the-dust."],
  kweepie: ["Is that... the fucking doll?!", "Kelly, I'm gonna kill you.", "Stop GIGGLING, you creepy little bitch!", "I see you, you porcelain piece of shit."],
  snatch: ["HEY! Give back my burgers!", "That asshole stole our steakburgers!", "Nobody steals from the reunion!"],
};
export const KENNEDY = {
  arrive: [
    "Babe! I brought the whole collection. Yes, even the one you said we didn't need. Who needs it now?",
    "Honey, I'm home! And I'm armed!",
    "Did somebody order a husband with a LOT of guns?",
  ],
  kill: [
    "That one had a coupon. Respect.",
    "I've been ready for this since 2012.",
    "Babe, don't look. I shot a guy in Crocs. It's bad.",
    "Another one for the group chat!",
    "Clean shot! Tell me I looked cool.",
    "I'm basically John Wick. A hungrier John Wick.",
    "Yeah! Who's the gun nut NOW?",
    "Sorry, buddy. Nothing personal. It's a little personal.",
    "Got 'im! Babe, did you see that?!",
    "That's for the credit card statement!",
    "Down goes Frazier!",
    "I'd say rest in peace, but... nah.",
  ],
  reload: ["Reloading! Cover me! And tell me I look cool!", "Mag out! Babe, I'm dry!", "Hold up, hold up, reloading!"],
  hurt: ["Ow! Babe, they bit my FLANNEL!", "That's gonna leave a mark!", "Okay, OW."],
  down: ["Tell my rifles I loved them. Equally. Except the tan one.", "I'm down! I'm DOWN! I'm fine. I'm not fine.", "Babe... I see a light... it's a Freddo's sign..."],
  up: ["I'm up! I'm good! That never happened.", "Walk it off, Kennedy. Walk it off.", "Back in it, baby!"],
  revive: ["Get UP. The reunion has a potato salad situation and I can't handle it alone.", "Babe! Babe! Wake up! I can't carry 120 burgers by myself!"],
  burger: ["Burgers! Babe, I'm eating one. Just one.", "Steakburger secured. I deserve this one.", "That's a W."],
  idle: ["You know what this needs? A tailgate.", "I'm just saying, if I'd bought the OTHER rifle...", "Babe, we should do this every weekend.", "Your mom's gonna be so mad she missed this.", "I'm counting kills. I'm winning, by the way."],
  boss: ["Big one! Light it UP!", "Oh, that's a boss. Babe, that's a BOSS!", "Aim for the... everything!"],
};
export const RULES = [
  [1, 'Never turn your back on a "stable" patient.'],
  [2, "Gloves on. You don't know where that zombie's been. Actually you do. Everywhere."],
  [3, 'Hand hygiene: wash before AND after every headshot.'],
  [4, "If it bites, it's not a \"difficult patient.\" Stop writing it up and shoot it."],
  [5, 'Never accept gifts from Kelly.'],
  [6, 'Steakburgers are morale. Morale is ammo.'],
  [7, "When in doubt, aim higher. The brain's up there. Usually."],
  [8, "Don't feed the doll. Don't look at the doll. Don't talk about the doll."],
  [9, 'Bedpans are a melee weapon if you believe in yourself.'],
  [10, 'Clock out alive.'],
];
